name: Deploy Rating

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Gen Rating
        run: |
          pnpm i
          pnpm gen_rating
          mkdir output
          mv rating-data ./output/

      - name: Deploy to deploy-pages
        if: ${{ github.event_name != 'pull_request' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
          publish_branch: rating-data
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: 🚀 Deploying to rating-data @ ${{ github.sha }}

      - name: Deploy
        if: ${{ github.event_name != 'pull_request' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            bash <(curl -s -L https://raw-github.dup4.com/Dup4/bash-script-snippet/main/deploy_gh_pages.sh)
            -r xcpcio/board-data
            -d /var/docker-data/nginx/www/xcpcio
            -b rating-data
            -p github.dup4.com

      - name: Deploy I18n
        if: ${{ github.event_name != 'pull_request' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_I18N }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            bash <(curl -s -L https://raw.github.com/Dup4/bash-script-snippet/main/deploy_gh_pages.sh)
            -r xcpcio/board-data
            -d /var/docker-data/nginx/www/xcpcio
            -b rating-data
